/* ============================================================
   DEPRECATED — do not edit this file.

   Application logic lives under /src (ES modules):
     - /src/main.js      entry point
     - /src/config.js    version & constants
     - /src/firebase.js  Firebase init
     - /src/icons.js     SVG icons
     - /src/app.js       app logic

   index.html loads: <script type="module" src="/src/main.js"></script>
   ============================================================ */
console.warn('[erp] js/app.js is deprecated; entry point is /src/main.js');
